DELETE http://localhost:3001/api/persons/123


GET http://localhost:3001/api/persons

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "asdfsdfsdfdfsdf",
  "number": "30238023434"
}